### ISSUE TITLE
Converting models to VST3 plugin

### ISSUE THREAD

**Issue by creativeguitar** [csteinmetz1/steerable-nafx#3]
Thank you for working on this project! I have been learning a lot related to Machine Learning thanks to you. 
Any ideas how to convert the PT file I get after training to a VST3 plugin ? 
Also where can I get more info on how to tweak the TCN model training parameters (what each parameter means) ?

**Comment by csteinmetz1** [comment]
Hey @creativeguitar, thanks for checking out the repo. 

I think the path towards getting the model into VST could be a bit tough. It is possible, but there are also potential issues with runtime since in this project all the models are built to run offline and not optimized for real-time processing. However, if you pick the right network size (small enough) it is possible. 

One route is to use [libtorch](https://pytorch.org/cppdocs/installing.html). I have done this with a previous project, in which case you have to convert the .pt to a torchscript file by tracing it. There is a tutorial on how to do that in the libtorch docs. For reference, you could checkout another project I worked on where I did that, but it may be a bit out of date now (https://github.com/csteinmetz1/ronn).  

Another option would be to try and convert this model to work with a framework like [RTNeural](https://github.com/jatinchowdhury18/RTNeural), but that won't be a straightforward path, since the network architecture used in this project may not be fully supported with their current features. The key part is having a way to handle the FiLM layers and residual connections. 

Sorry I can't give you a clearer direction, but hopefully some of this info is helpful.

**Comment by csteinmetz1** [comment]
Wanted to update this thread by pointing to the recent project at https://neutone.space/ which aims to provide a more straightforward way to turn PyTorch audio models into a VST.
